export const CATALOG_FILTER_CONSTANTS = {
  AVAILABILITY: [
    { label: "Download", value: "Download"},
    { label: "External Link", value: "External_Link"},
    { label: "Order Only", value: "Order_Only"},
    { label: "WMS Service", value: "WMS_Service"},
  ],
  CATEGORIES: [
    { value: "Basemap", label: "Basemap"},
    { value: "Elevation", label: "Elevation"},
    { value: "Historic_Imagery", label: "Historic Imagery"},
    { value: "Hydrography", label: "Hydrography"},
    { value: "Imagery", label: "Imagery"},
    { value: "Land_Cover", label: "Land Cover"},
    { value: "Lidar", label: "Lidar"},
    { value: "Reference_Grid", label: "Reference Grid"},
    { value: "Transportation", label: "Transportation"},
    { value: "Weather", label: "Weather"},
    { value: "Bathymetry", label: "Bathymetry"},
  ],
  FILETYPE: [
    { value: "DEM", label: "DEM" },
    { value: "DWG", label: "DWG" },
    { value: "ECW", label: "ECW" },
    { value: "ESRI_Grid", label: "ESRI Grid" },
    { value: "GDB", label: "GDB" },
    { value: "GEOJSON", label: "GEOJSON" },
    { value: "IMG", label: "IMG" },
    { value: "JP2", label: "JP2" },
    { value: "JPG", label: "JPG" },
    { value: "LAZ", label: "LAZ" },
    { value: "MrSID", label: "MrSID" },
    { value: "SHP", label: "SHP" },
    { value: "TIFF", label: "TIFF" },
    { value: "TOPOJSON", label: "TOPOJSON" },
  ],
};
